# Jekyll main setup page
title: Matthew Burton Portfolio 

email: 36slices@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  A webpage designed to track my progress as a portfolio and store my journals/blog posts.
  "Kaizen: continuous improvement."

baseurl: "" # the subpath of your site, e.g. /blog

url: "www.mattburton36.com" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  mattburt36

# Build settings
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

title-logo: images\PortfolioImage.png
